fo_request_user_has_club:
    path:     /sendrequest
    defaults: { _controller: FfjvFoBundle:UserHasClub:sendRequestToJoin }
    methods: POST

fo_request_user_has_club_edit_request:
    path:     /{membersHasClubId}/editRequest
    defaults: { _controller: "FfjvFoBundle:UserHasClub:editJoinRequest" }

fo_user_has_club_set_request:
    path:     /setrequest
    defaults: { _controller: FfjvFoBundle:UserHasClub:setRequestJoinClub}
    methods: POST

fo_user_has_club_edit_member:
    path:     /{memberId}/edit
    defaults: { _controller: FfjvFoBundle:UserHasClub:editMember}

fo_user_has_club_update_member:
    path:     /{memberId}/update
    defaults: { _controller: FfjvFoBundle:UserHasClub:updateMember}
    methods: PUT

fo_user_has_club_remove_member:
    path:     /{memberId}/remove
    defaults: { _controller: FfjvFoBundle:UserHasClub:removeMember}
    methods: DELETE