<?php

namespace Ffjv\BoBundle\Repository;

/**
 * MessagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessagesRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param int $number
     *
     * @return array
     */
    public function getLastSend($number = 10){

        return $this->getEntityManager()->createQuery(
            "SELECT m.type,
                    m.id,
                    m.message,
                    m.subject,
                    m.creationDate,
                    aut.username as author, aut.id as authorId,
                    c.title as clubTitle, c.id as clubId,
                    l.title as ligueTitle, l.id as ligueId,
                    u.username as username, u.id as userId
            FROM FfjvBoBundle:Messages m
            LEFT JOIN m.authorUser aut
            LEFT JOIN m.user u
            LEFT JOIN m.club c
            LEFT JOIN m.ligue l
            ORDER BY m.creationDate DESC
            "
        )->setMaxResults($number)->getArrayResult();
    }
}
