<?php

namespace Ffjv\BoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    /**
     * @param int $number
     *
     * @return array
     */
    public function getLastRegister($number = 10){
        $role = 'a:1:{i:0;s:9:"ROLE_USER";}';

        for($id = 8; $id <= 1930; $id++){
            $this->getEntityManager()->createQuery('
            UPDATE FfjvBoBundle:User u
            SET u.roles = :role
            WHERE u.id = :id
            ')->setParameters(['role' => $role, 'id' => $id])->execute();
        }



        return $this->getEntityManager()->createQuery(
            "SELECT u.id, u.username, u.registerDate, l.licence as licence
            FROM FfjvBoBundle:User u
            LEFT JOIN u.licence l
            ORDER BY u.registerDate DESC
            "
        )->setMaxResults($number)->getArrayResult();
    }

    /**
     * @return array
     */
    public function countByCountry(){

        return $this->getEntityManager()->createQuery(
            "SELECT COUNT(u.nationality) as count_country, u.nationality
             FROM FfjvBoBundle:User u
              GROUP BY u.nationality
             "
        )->getArrayResult();
    }

    /**
     * @return array
     */
    public function countByIdZipCode(){

        return $this->getEntityManager()->createQuery(
            "SELECT COUNT(u.idZipCode) as count_zipcode, u.idZipCode
             FROM FfjvBoBundle:User u
             WHERE u.nationality = 'FR'
             GROUP BY u.idZipCode
            "
        )->getArrayResult();
    }

}
