parameters:
    path_lib: "public/lib/"
    path_component: "public/components/elements/"
    component_array:
        proto-element:
            - "polymer/polymer.html"
            - "paper-material/paper-material.html"
        tabs-element:
            - "polymer/polymer.html"
            - "iron-pages/iron-pages.html"
            - "iron-ajax/iron-ajax.html"
            - "paper-tabs/paper-tabs.html"
            - "paper-tabs/paper-tab.html"
        button_dialog_async-element:
            - "polymer/polymer.html"
            - "iron-signals/iron-signals.html"
            - "paper-button/paper-button.html"
        dialog_async-element:
            - "polymer/polymer.html"
            - "iron-signals/iron-signals.html"
            - "iron-icons/iron-icons.html"
            - "paper-dialog/paper-dialog.html"
            - "paper-dialog-scrollable/paper-dialog-scrollable.html"
        pages-element:
            - "polymer/polymer.html"
            - "iron-pages/iron-pages.html"
            - "iron-ajax/iron-ajax.html"
            - "neon-animation/neon-animated-pages.html"
            - "neon-animation/neon-animatable.html"
            - "neon-animation/neon-animations.html"
            - "iron-icons/iron-icons.html"
        toast-element:
            - "polymer/polymer.html"
            - "paper-toast/paper-toast.html"

services:
    web.component.twig_extension:
        class: WebComponentBundle\Twig\WebComponentTwigExtension
        public: false
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }
    web_component:
        class: WebComponentBundle\Service\WebComponentService
        arguments: ["@service_container", "@assets.packages", "%path_lib%", "%path_component%", "%component_array%"]