parameters:
    path_lib: "public/lib/"
    path_component: "public/components/"
    component_array:
        proto-element:
            - "polymer/polymer.html"
            - "paper-material/paper-material.html"
services:
    web.component.twig_extension:
        class: WebComponentBundle\Twig\WebComponentTwigExtension
        public: false
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }
    web_component:
        class: WebComponentBundle\Service\WebComponentService
        arguments: ["@service_container", "@assets.packages", "%path_lib%", "%path_component%", "%component_array%"]