# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FfjvBoBundle\Entity\User:
            algorithm:          sha512
            encode_as_base64:   true
            iterations:         11023

    acl:
        connection: default

    role_hierarchy:
        ROLE_USER_CONFIRMED:  ROLE_USER
        ROLE_ADMIN:           ROLE_USER_CONFIRMED
        ROLE_SUPER_ADMIN:     [ROLE_USER_CONFIRMED, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
#       in_memory:
#           memory:
#               users:
#                   user:  { password: userpass, roles: ['ROLE_USER'] }
#                   admin: { password: adminpass, roles: ['ROLE_ADMIN'] }
        main:
            entity:
                class: FfjvBoBundle\Entity\User
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
#           provider: in_memory
            provider: main
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: /status
            logout:
                path:   logout
                target: /

    access_control:
        - { path: ^/profile, roles:  ROLE_USER_CONFIRMED }
        - { path: ^/clubs, roles:  ROLE_USER_CONFIRMED }
        - { path: ^/members, roles:  ROLE_USER_CONFIRMED }
        - { path: ^/club, roles:  ROLE_USER_CONFIRMED }
        - { path: ^/team, roles:  ROLE_USER_CONFIRMED }
        - { path: ^/administration, roles: ROLE_ADMIN }
        - { path: ^/webcomponent, roles: ROLE_ADMIN }