<?php

namespace FfjvBoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClubsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubsRepository extends EntityRepository
{
    /**
     * @param int $number
     *
     * @return array
     */
    public function getLastCreated($number = 10){

        return $this->getEntityManager()->createQuery(
            "SELECT c.id, c.title, c.creationDate, u.username as username, u.id as userId
            FROM FfjvBoBundle:Clubs c
            JOIN c.user u
            ORDER BY c.creationDate DESC
            "
        )->setMaxResults($number)->getArrayResult();
    }

    /**
     * @return array
     */
    public function countByIdZipCode(){

        return $this->getEntityManager()->createQuery(
            "SELECT COUNT(c.idZipCode) as count_zipcode, c.idZipCode
             FROM FfjvBoBundle:Clubs c
             WHERE c.country = 'FR'
             GROUP BY c.idZipCode
            "
        )->getArrayResult();
    }

    /**
     * @param int $clubId
     *
     * @return array
     */
    public function findLigueByClub($clubId = 0){
        return $this->getEntityManager()->createQuery(
            "SELECT l
            FROM FfjvBoBundle:Ligues l
            JOIN l.clubs c
            WHERE c.id = $clubId
            "
        )->getArrayResult();
    }

    /**
     * @param $clubId
     *
     * @return mixed
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function countMemberActive($clubId){
        return $this->getEntityManager()->createQuery(
            "SELECT COUNT(m) as count_active
            FROM FfjvBoBundle:Clubs c
            JOIN c.members m
            JOIN m.user u
            WHERE c.id = $clubId
            AND u.status = 1
            "
        )->getSingleResult();
    }
}
