<?php

namespace FfjvBoBundle\Repository;

/**
 * LicencesClubsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LicencesClubsRepository extends \Doctrine\ORM\EntityRepository
{
}
