<?php

namespace FfjvBoBundle\Repository;

/**
 * LicencesUsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LicencesUsersRepository extends \Doctrine\ORM\EntityRepository
{
}
