<?php

namespace FfjvBoBundle\Repository;

/**
 * LicencesTeamsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LicencesTeamsRepository extends \Doctrine\ORM\EntityRepository
{
}
