<?php

namespace FfjvBoBundle\Repository;

/**
 * LiguesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LiguesRepository extends \Doctrine\ORM\EntityRepository
{
}
