<?php

namespace FfjvBoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserHasTeamsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserHasTeamsRepository extends \Doctrine\ORM\EntityRepository
{
}
