<?php

namespace FfjvBoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    /**
     * @return array
     */
    public function getAllUser(){
        return $this->getEntityManager()->createQuery(
            "SELECT u.id, u.username, u.registerDate, u.roles, u.email, u.nationality, u.firstName, u.lastName, u.registerDate, u.lastUpdate, l.licence as licence
            FROM FfjvBoBundle:User u
            LEFT JOIN u.licence l
            ORDER BY u.registerDate DESC
            "
        )->getArrayResult();
    }

    /**
     * @param int $number
     *
     * @return array
     */
    public function getLastRegister($number = 10){

        return $this->getEntityManager()->createQuery(
            "SELECT u.id, u.username, u.registerDate, l.licence as licence
            FROM FfjvBoBundle:User u
            LEFT JOIN u.licence l
            ORDER BY u.registerDate DESC
            "
        )->setMaxResults($number)->getArrayResult();
    }

    /**
     * @return array
     */
    public function countByCountry(){

        return $this->getEntityManager()->createQuery(
            "SELECT COUNT(u.nationality) as count_country, u.nationality
             FROM FfjvBoBundle:User u
             GROUP BY u.nationality
             "
        )->getArrayResult();
    }

    /**
     * @return array
     */
    public function countByIdZipCode(){

        return $this->getEntityManager()->createQuery(
            "SELECT COUNT(u.idZipCode) as count_zipcode, u.idZipCode
             FROM FfjvBoBundle:User u
             WHERE u.nationality = 'FR'
             GROUP BY u.idZipCode
            "
        )->getArrayResult();
    }

}