<?php

namespace FfjvBoBundle\Repository;

/**
 * WeezeventApiLog
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeezeventApiLog extends \Doctrine\ORM\EntityRepository
{
}
