ffjv_bo_evenements_index:
    path:     /
    defaults: { _controller: "FfjvBoBundle:Evenements:index" }
    methods:  GET

ffjv_bo_evenements_show:
    path:     /{id}/show
    defaults: { _controller: "FfjvBoBundle:Evenements:show" }
    methods:  GET

ffjv_bo_evenements_new:
    path:     /new
    defaults: { _controller: "FfjvBoBundle:Evenements:new" }
    methods:  [GET, POST]

ffjv_bo_evenements_edit:
    path:     /{id}/edit
    defaults: { _controller: "FfjvBoBundle:Evenements:edit" }
    methods:  [GET, POST]

ffjv_bo_evenements_delete:
    path:     /{id}/delete
    defaults: { _controller: "FfjvBoBundle:Evenements:delete" }
    methods:  DELETE

ffjv_bo_evenements_listevent:
    path:     /getlist
    defaults: { _controller: "FfjvBoBundle:Evenements:getEventClub"}
    methods: POST
